logging:
    level:
        root: WARN
        zserio: INFO

server:
    port: 5000

spring:
    application:
        name: zserio-calculator-service-server

    messages:
        encoding: UTF-8 
        fallback-to-system-locale: true 

    mvc:
      async:
        request-timeout: -1

springdoc:
    api-docs:
        enabled: true
        path: /api-docs

    swagger-ui:
        disable-swagger-default-url: true
        enabled: true
        operationsSorter: alpha
        path: /api-ui.html
