feign:
    client:
        config:
            default:
                connectTimeout: 60000
                decoder: zserio.service.rest.java.feign.ZserioFeignDecoder
                encoder: zserio.service.rest.java.feign.ZserioFeignEncoder
                loggerLevel: basic
                readTimeout: 60000
    url: localhost:5000

logging:
    level:
        root: WARN
        zserio: INFO

spring:
    application:
        name: zserio-calculator-service-client

    messages:
        encoding: UTF-8 
        fallback-to-system-locale: true 

    mvc:
        async:
            request-timeout: -1
