name: Windows

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_windows:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["windows-latest"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Build Zserio Java Service Rest
      run: mvn package -Dmaven.repo.local="build/download"
      shell: bash

    - name: Test Zserio Java Service Rest
      run: |
        java -jar calculator-server/target/calculator-server-0.0.1-SNAPSHOT.jar &
        sleep 10
        { echo "p"; sleep 1; echo "100"; sleep 1; echo "q"; } |
               java -jar calculator-client/target/calculator-client-0.0.1-SNAPSHOT.jar | grep "10000"
        { echo "s"; sleep 1; echo "100"; sleep 1; echo "q"; } |
                java -jar calculator-client/target/calculator-client-0.0.1-SNAPSHOT.jar | grep "10.0"
        kill $(jobs -p)
      shell: bash

    - name: Archive Zserio Java Service Rest classes
      uses: actions/upload-artifact@v4
      with:
        name: zserio-service-rest-java-${{matrix.os}}
        path: |
          calculator-server/target/*.jar
          calculator-client/target/*.jar
